package com.management.entities;
// Generated Mar 4, 2018 4:33:07 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author Zivko Stanisic
 * Actor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "actor", catalog = "isa")
public class Actor implements java.io.Serializable {

	private int acId;
	private String acName;
	private String acSurname;
	@SuppressWarnings("rawtypes")
	private Set actorperformanceses = new HashSet(0);

	public Actor() {
	}

	public Actor(int acId, String acName, String acSurname) {
		this.acId = acId;
		this.acName = acName;
		this.acSurname = acSurname;
	}

	@SuppressWarnings("rawtypes")
	public Actor(int acId, String acName, String acSurname, Set actorperformanceses) {
		this.acId = acId;
		this.acName = acName;
		this.acSurname = acSurname;
		this.actorperformanceses = actorperformanceses;
	}

	@Id

	@Column(name = "AC_ID", unique = true, nullable = false)
	public int getAcId() {
		return this.acId;
	}

	public void setAcId(int acId) {
		this.acId = acId;
	}

	@Column(name = "AC_NAME", nullable = false, length = 50)
	public String getAcName() {
		return this.acName;
	}

	public void setAcName(String acName) {
		this.acName = acName;
	}

	@Column(name = "AC_SURNAME", nullable = false, length = 50)
	public String getAcSurname() {
		return this.acSurname;
	}

	public void setAcSurname(String acSurname) {
		this.acSurname = acSurname;
	}

	@SuppressWarnings("rawtypes")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actor")
	public Set getActorperformanceses() {
		return this.actorperformanceses;
	}

	@SuppressWarnings("rawtypes")
	public void setActorperformanceses(Set actorperformanceses) {
		this.actorperformanceses = actorperformanceses;
	}

}
