package com.management.entities;

// Generated Apr 2, 2018 4:06:14 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "actor", catalog = "isa")
public class Actor implements java.io.Serializable {

	private int acId;
	private String acName;
	private String acSurname;
	private Set<Actorperformances> actorperformanceses = new HashSet<Actorperformances>(0);

	public Actor() {
	}

	public Actor(int acId, String acName, String acSurname) {
		this.acId = acId;
		this.acName = acName;
		this.acSurname = acSurname;
	}

	public Actor(int acId, String acName, String acSurname,
			Set<Actorperformances> actorperformanceses) {
		this.acId = acId;
		this.acName = acName;
		this.acSurname = acSurname;
		this.actorperformanceses = actorperformanceses;
	}

	@Id
	@Column(name = "AC_ID", unique = true, nullable = false)
	public int getAcId() {
		return this.acId;
	}

	public void setAcId(int acId) {
		this.acId = acId;
	}

	@Column(name = "AC_NAME", nullable = false, length = 50)
	public String getAcName() {
		return this.acName;
	}

	public void setAcName(String acName) {
		this.acName = acName;
	}

	@Column(name = "AC_SURNAME", nullable = false, length = 50)
	public String getAcSurname() {
		return this.acSurname;
	}

	public void setAcSurname(String acSurname) {
		this.acSurname = acSurname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actor")
	public Set<Actorperformances> getActorperformanceses() {
		return this.actorperformanceses;
	}

	public void setActorperformanceses(
			Set<Actorperformances> actorperformanceses) {
		this.actorperformanceses = actorperformanceses;
	}

}
