package com.management.entities;

// Generated Apr 20, 2018 9:30:21 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Actorperformances generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "actorperformances", catalog = "isa")
public class Actorperformances implements java.io.Serializable {

	private int apId;
	private Actor actor;
	private Performance performance;

	public Actorperformances() {
	}

	public Actorperformances(int apId, Actor actor, Performance performance) {
		this.apId = apId;
		this.actor = actor;
		this.performance = performance;
	}

	@Id
	@GenericGenerator(name="generator" , strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "AP_ID", unique = true, nullable = false)
	public int getApId() {
		return this.apId;
	}

	public void setApId(int apId) {
		this.apId = apId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AC_ID", nullable = false)
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PER_ID", nullable = false)
	public Performance getPerformance() {
		return this.performance;
	}

	public void setPerformance(Performance performance) {
		this.performance = performance;
	}

}
