package com.management.entities;
// Generated Feb 23, 2018 5:00:46 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * @author Zivko Stanisic
 * CinemaTheatre generated by hbm2java
 */
@SuppressWarnings("serial")
public class CinemaTheatre implements java.io.Serializable {

	private int ctId;
	private String ctName;
	private String ctPhone;
	private String ctAdress;
	private String ctDescription;
	@SuppressWarnings("rawtypes")
	private Set halls = new HashSet(0);

	public CinemaTheatre() {
	}

	public CinemaTheatre(int ctId) {
		this.ctId = ctId;
	}

	@SuppressWarnings("rawtypes")
	public CinemaTheatre(int ctId, String ctName, String ctPhone, String ctAdress, String ctDescription, Set halls) {
		this.ctId = ctId;
		this.ctName = ctName;
		this.ctPhone = ctPhone;
		this.ctAdress = ctAdress;
		this.ctDescription = ctDescription;
		this.halls = halls;
	}

	public int getCtId() {
		return this.ctId;
	}

	public void setCtId(int ctId) {
		this.ctId = ctId;
	}

	public String getCtName() {
		return this.ctName;
	}

	public void setCtName(String ctName) {
		this.ctName = ctName;
	}

	public String getCtPhone() {
		return this.ctPhone;
	}

	public void setCtPhone(String ctPhone) {
		this.ctPhone = ctPhone;
	}

	public String getCtAdress() {
		return this.ctAdress;
	}

	public void setCtAdress(String ctAdress) {
		this.ctAdress = ctAdress;
	}

	public String getCtDescription() {
		return this.ctDescription;
	}

	public void setCtDescription(String ctDescription) {
		this.ctDescription = ctDescription;
	}

	@SuppressWarnings("rawtypes")
	public Set getHalls() {
		return this.halls;
	}

	@SuppressWarnings("rawtypes")
	public void setHalls(Set halls) {
		this.halls = halls;
	}

}
