package com.management.entities;
// Generated Mar 14, 2018 9:09:33 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * @author Zivko Stanisic
 * CinemaTheatre generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "cinema_theatre", catalog = "isa")
public class CinemaTheatre implements java.io.Serializable {

	private int ctId;
	private String ctName;
	private String ctStateid;
	private Integer ctPhone;
	private String ctAdress;
	private String ctDescription;
	private Set<Hall> halls = new HashSet<Hall>(0);

	public CinemaTheatre() {
	}

	public CinemaTheatre(int ctId) {
		this.ctId = ctId;
	}

	public CinemaTheatre(int ctId, String ctName, String ctStateid, Integer ctPhone, String ctAdress,
			String ctDescription, Set<Hall> halls) {
		this.ctId = ctId;
		this.ctName = ctName;
		this.ctStateid = ctStateid;
		this.ctPhone = ctPhone;
		this.ctAdress = ctAdress;
		this.ctDescription = ctDescription;
		this.halls = halls;
	}

	@Id
	@GenericGenerator(name="generator" , strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "CT_ID", unique = true, nullable = false)
	public int getCtId() {
		return this.ctId;
	}

	public void setCtId(int ctId) {
		this.ctId = ctId;
	}

	@Column(name = "CT_NAME", length = 50)
	public String getCtName() {
		return this.ctName;
	}

	public void setCtName(String ctName) {
		this.ctName = ctName;
	}

	@Column(name = "CT_STATEID", length = 3)
	public String getCtStateid() {
		return this.ctStateid;
	}

	public void setCtStateid(String ctStateid) {
		this.ctStateid = ctStateid;
	}

	@Column(name = "CT_PHONE")
	public Integer getCtPhone() {
		return this.ctPhone;
	}

	public void setCtPhone(Integer ctPhone) {
		this.ctPhone = ctPhone;
	}

	@Column(name = "CT_ADRESS", length = 50)
	public String getCtAdress() {
		return this.ctAdress;
	}

	public void setCtAdress(String ctAdress) {
		this.ctAdress = ctAdress;
	}

	@Column(name = "CT_DESCRIPTION", length = 200)
	public String getCtDescription() {
		return this.ctDescription;
	}

	public void setCtDescription(String ctDescription) {
		this.ctDescription = ctDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cinemaTheatre")
	public Set<Hall> getHalls() {
		return this.halls;
	}

	public void setHalls(Set<Hall> halls) {
		this.halls = halls;
	}

}
