package com.management.entities;

// Generated Apr 2, 2018 4:06:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "event", catalog = "isa")
public class Event implements java.io.Serializable {

	private int eventId;
	private Hall hall;
	private Performance performance;
	private Date eventDate;
	private Set<History> histories = new HashSet<History>(0);

	public Event() {
	}

	public Event(int eventId, Hall hall, Performance performance, Date eventDate) {
		this.eventId = eventId;
		this.hall = hall;
		this.performance = performance;
		this.eventDate = eventDate;
	}

	public Event(int eventId, Hall hall, Performance performance,
			Date eventDate, Set<History> histories) {
		this.eventId = eventId;
		this.hall = hall;
		this.performance = performance;
		this.eventDate = eventDate;
		this.histories = histories;
	}

	@Id
	@Column(name = "EVENT_ID", unique = true, nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HALL_ID", nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PER_ID", nullable = false)
	public Performance getPerformance() {
		return this.performance;
	}

	public void setPerformance(Performance performance) {
		this.performance = performance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EVENT_DATE", nullable = false, length = 19)
	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

}
