package com.management.entities;
// Generated Apr 18, 2018 12:50:36 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Event generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "event", catalog = "isa")
public class Event implements java.io.Serializable {

	private int eventId;
	private Hall hall;
	private Performance performance;
	private Date eventDate;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);
	private Set<History> histories = new HashSet<History>(0);

	public Event() {
	}

	public Event(int eventId, Hall hall, Performance performance, Date eventDate) {
		this.eventId = eventId;
		this.hall = hall;
		this.performance = performance;
		this.eventDate = eventDate;
	}

	public Event(int eventId, Hall hall, Performance performance, Date eventDate, Set<Ticket> tickets,
			Set<History> histories) {
		this.eventId = eventId;
		this.hall = hall;
		this.performance = performance;
		this.eventDate = eventDate;
		this.tickets = tickets;
		this.histories = histories;
	}

	@Id
	@GenericGenerator(name="generator" , strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "EVENT_ID", unique = true, nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HALL_ID", nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PER_ID", nullable = false)
	public Performance getPerformance() {
		return this.performance;
	}

	public void setPerformance(Performance performance) {
		this.performance = performance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EVENT_DATE", nullable = false, length = 19)
	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

}
