package com.management.entities;
// Generated Mar 14, 2018 9:09:33 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author Zivko Stanisic
 * FanZone generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "fan_zone", catalog = "isa")
public class FanZone implements java.io.Serializable {

	private int fanZoneId;
	private String fanZoneName;
	private Set<Props> propses = new HashSet<Props>(0);

	public FanZone() {
	}

	public FanZone(int fanZoneId) {
		this.fanZoneId = fanZoneId;
	}

	public FanZone(int fanZoneId, String fanZoneName, Set<Props> propses) {
		this.fanZoneId = fanZoneId;
		this.fanZoneName = fanZoneName;
		this.propses = propses;
	}

	@Id

	@Column(name = "FAN_ZONE_ID", unique = true, nullable = false)
	public int getFanZoneId() {
		return this.fanZoneId;
	}

	public void setFanZoneId(int fanZoneId) {
		this.fanZoneId = fanZoneId;
	}

	@Column(name = "FAN_ZONE_NAME", length = 50)
	public String getFanZoneName() {
		return this.fanZoneName;
	}

	public void setFanZoneName(String fanZoneName) {
		this.fanZoneName = fanZoneName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fanZone")
	public Set<Props> getPropses() {
		return this.propses;
	}

	public void setPropses(Set<Props> propses) {
		this.propses = propses;
	}

}
