package com.management.entities;
// Generated Feb 23, 2018 5:00:46 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * @author Zivko Stanisic
 * FanZone generated by hbm2java
 */
@SuppressWarnings("serial")
public class FanZone implements java.io.Serializable {

	private int fanZoneId;
	private String fanZoneName;
	@SuppressWarnings("rawtypes")
	private Set propses = new HashSet(0);

	public FanZone() {
	}

	public FanZone(int fanZoneId) {
		this.fanZoneId = fanZoneId;
	}

	@SuppressWarnings("rawtypes")
	public FanZone(int fanZoneId, String fanZoneName, Set propses) {
		this.fanZoneId = fanZoneId;
		this.fanZoneName = fanZoneName;
		this.propses = propses;
	}

	public int getFanZoneId() {
		return this.fanZoneId;
	}

	public void setFanZoneId(int fanZoneId) {
		this.fanZoneId = fanZoneId;
	}

	public String getFanZoneName() {
		return this.fanZoneName;
	}

	public void setFanZoneName(String fanZoneName) {
		this.fanZoneName = fanZoneName;
	}

	@SuppressWarnings("rawtypes")
	public Set getPropses() {
		return this.propses;
	}

	@SuppressWarnings("rawtypes")
	public void setPropses(Set propses) {
		this.propses = propses;
	}

}
