package com.management.entities;
// Generated Feb 22, 2018 10:07:38 PM by Hibernate Tools 5.2.3.Final

/**
 * @author Zivko Stanisic 
 * Friendslist generated by hbm2java
 */
@SuppressWarnings("serial")
public class Friendslist implements java.io.Serializable {

	private int friendsId;
	private User userByUseUserId2;
	private User userByUseUserId;
	private User userByUserId;
	private char friendsStatus;

	public Friendslist() {
	}

	public Friendslist(int friendsId, User userByUseUserId2, User userByUseUserId, User userByUserId,
			char friendsStatus) {
		this.friendsId = friendsId;
		this.userByUseUserId2 = userByUseUserId2;
		this.userByUseUserId = userByUseUserId;
		this.userByUserId = userByUserId;
		this.friendsStatus = friendsStatus;
	}

	public int getFriendsId() {
		return this.friendsId;
	}

	public void setFriendsId(int friendsId) {
		this.friendsId = friendsId;
	}

	public User getUserByUseUserId2() {
		return this.userByUseUserId2;
	}

	public void setUserByUseUserId2(User userByUseUserId2) {
		this.userByUseUserId2 = userByUseUserId2;
	}

	public User getUserByUseUserId() {
		return this.userByUseUserId;
	}

	public void setUserByUseUserId(User userByUseUserId) {
		this.userByUseUserId = userByUseUserId;
	}

	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	public char getFriendsStatus() {
		return this.friendsStatus;
	}

	public void setFriendsStatus(char friendsStatus) {
		this.friendsStatus = friendsStatus;
	}

}
