package com.management.entities;
// Generated Mar 4, 2018 4:33:07 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author Zivko Stanisic
 * Hall generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "hall", catalog = "isa")
public class Hall implements java.io.Serializable {

	private int hallId;
	private CinemaTheatre cinemaTheatre;
	private String hallName;
	@SuppressWarnings("rawtypes")
	private Set events = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set seats = new HashSet(0);

	public Hall() {
	}

	public Hall(int hallId, CinemaTheatre cinemaTheatre, String hallName) {
		this.hallId = hallId;
		this.cinemaTheatre = cinemaTheatre;
		this.hallName = hallName;
	}

	@SuppressWarnings("rawtypes")
	public Hall(int hallId, CinemaTheatre cinemaTheatre, String hallName, Set events, Set seats) {
		this.hallId = hallId;
		this.cinemaTheatre = cinemaTheatre;
		this.hallName = hallName;
		this.events = events;
		this.seats = seats;
	}

	@Id

	@Column(name = "HALL_ID", unique = true, nullable = false)
	public int getHallId() {
		return this.hallId;
	}

	public void setHallId(int hallId) {
		this.hallId = hallId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CT_ID", nullable = false)
	public CinemaTheatre getCinemaTheatre() {
		return this.cinemaTheatre;
	}

	public void setCinemaTheatre(CinemaTheatre cinemaTheatre) {
		this.cinemaTheatre = cinemaTheatre;
	}

	@Column(name = "HALL_NAME", nullable = false, length = 50)
	public String getHallName() {
		return this.hallName;
	}

	public void setHallName(String hallName) {
		this.hallName = hallName;
	}

	@SuppressWarnings("rawtypes")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set getEvents() {
		return this.events;
	}

	@SuppressWarnings("rawtypes")
	public void setEvents(Set events) {
		this.events = events;
	}

	@SuppressWarnings("rawtypes")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set getSeats() {
		return this.seats;
	}

	@SuppressWarnings("rawtypes")
	public void setSeats(Set seats) {
		this.seats = seats;
	}

}
