package com.management.entities;
// Generated Feb 23, 2018 5:00:46 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * @author Zivko Stanisic
 * Hall generated by hbm2java
 */
@SuppressWarnings("serial")
public class Hall implements java.io.Serializable {

	private int hallId;
	private CinemaTheatre cinemaTheatre;
	private String hallName;
	@SuppressWarnings("rawtypes")
	private Set events = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set seats = new HashSet(0);

	public Hall() {
	}

	public Hall(int hallId, CinemaTheatre cinemaTheatre, String hallName) {
		this.hallId = hallId;
		this.cinemaTheatre = cinemaTheatre;
		this.hallName = hallName;
	}

	@SuppressWarnings("rawtypes")
	public Hall(int hallId, CinemaTheatre cinemaTheatre, String hallName, Set events, Set seats) {
		this.hallId = hallId;
		this.cinemaTheatre = cinemaTheatre;
		this.hallName = hallName;
		this.events = events;
		this.seats = seats;
	}

	public int getHallId() {
		return this.hallId;
	}

	public void setHallId(int hallId) {
		this.hallId = hallId;
	}

	public CinemaTheatre getCinemaTheatre() {
		return this.cinemaTheatre;
	}

	public void setCinemaTheatre(CinemaTheatre cinemaTheatre) {
		this.cinemaTheatre = cinemaTheatre;
	}

	public String getHallName() {
		return this.hallName;
	}

	public void setHallName(String hallName) {
		this.hallName = hallName;
	}

	@SuppressWarnings("rawtypes")
	public Set getEvents() {
		return this.events;
	}

	@SuppressWarnings("rawtypes")
	public void setEvents(Set events) {
		this.events = events;
	}

	@SuppressWarnings("rawtypes")
	public Set getSeats() {
		return this.seats;
	}

	@SuppressWarnings("rawtypes")
	public void setSeats(Set seats) {
		this.seats = seats;
	}

}
