package com.management.entities;
// Generated Feb 23, 2018 5:00:46 PM by Hibernate Tools 5.2.3.Final

/**
 * @author Zivko Stanisic
 * History generated by hbm2java
 */
@SuppressWarnings("serial")
public class History implements java.io.Serializable {

	private int historyId;
	private Event event;
	private User user;
	private int historyPrice;

	public History() {
	}

	public History(int historyId, Event event, User user, int historyPrice) {
		this.historyId = historyId;
		this.event = event;
		this.user = user;
		this.historyPrice = historyPrice;
	}

	public int getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(int historyId) {
		this.historyId = historyId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getHistoryPrice() {
		return this.historyPrice;
	}

	public void setHistoryPrice(int historyPrice) {
		this.historyPrice = historyPrice;
	}

}
