package com.management.entities;
// Generated Mar 14, 2018 9:09:33 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author Zivko Stanisic
 * History generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "history", catalog = "isa")
public class History implements java.io.Serializable {

	private int historyId;
	private Event event;
	private User user;
	private int historyPrice;

	public History() {
	}

	public History(int historyId, Event event, User user, int historyPrice) {
		this.historyId = historyId;
		this.event = event;
		this.user = user;
		this.historyPrice = historyPrice;
	}

	@Id

	@Column(name = "HISTORY_ID", unique = true, nullable = false)
	public int getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(int historyId) {
		this.historyId = historyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_ID", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "HISTORY_PRICE", nullable = false)
	public int getHistoryPrice() {
		return this.historyPrice;
	}

	public void setHistoryPrice(int historyPrice) {
		this.historyPrice = historyPrice;
	}

}
