package com.management.entities;
// Generated Mar 4, 2018 4:33:07 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author Zivko Stanisic
 * Performance generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "performance", catalog = "isa")
public class Performance implements java.io.Serializable {

	private int perId;
	private char perType;
	private String perGenre;
	private String perDirector;
	private int perDuration;
	private Date perCreationDate;
	private float perPrice;
	private int perRank;
	private byte[] perPoster;
	private String perDescription;
	@SuppressWarnings("rawtypes")
	private Set actorperformanceses = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set events = new HashSet(0);

	public Performance() {
	}

	public Performance(int perId, char perType, String perGenre, String perDirector, int perDuration,
			Date perCreationDate, float perPrice, int perRank) {
		this.perId = perId;
		this.perType = perType;
		this.perGenre = perGenre;
		this.perDirector = perDirector;
		this.perDuration = perDuration;
		this.perCreationDate = perCreationDate;
		this.perPrice = perPrice;
		this.perRank = perRank;
	}

	@SuppressWarnings("rawtypes")
	public Performance(int perId, char perType, String perGenre, String perDirector, int perDuration,
			Date perCreationDate, float perPrice, int perRank, byte[] perPoster, String perDescription,
			Set actorperformanceses, Set events) {
		this.perId = perId;
		this.perType = perType;
		this.perGenre = perGenre;
		this.perDirector = perDirector;
		this.perDuration = perDuration;
		this.perCreationDate = perCreationDate;
		this.perPrice = perPrice;
		this.perRank = perRank;
		this.perPoster = perPoster;
		this.perDescription = perDescription;
		this.actorperformanceses = actorperformanceses;
		this.events = events;
	}

	@Id

	@Column(name = "PER_ID", unique = true, nullable = false)
	public int getPerId() {
		return this.perId;
	}

	public void setPerId(int perId) {
		this.perId = perId;
	}

	@Column(name = "PER_TYPE", nullable = false, length = 1)
	public char getPerType() {
		return this.perType;
	}

	public void setPerType(char perType) {
		this.perType = perType;
	}

	@Column(name = "PER_GENRE", nullable = false, length = 30)
	public String getPerGenre() {
		return this.perGenre;
	}

	public void setPerGenre(String perGenre) {
		this.perGenre = perGenre;
	}

	@Column(name = "PER_DIRECTOR", nullable = false, length = 50)
	public String getPerDirector() {
		return this.perDirector;
	}

	public void setPerDirector(String perDirector) {
		this.perDirector = perDirector;
	}

	@Column(name = "PER_DURATION", nullable = false)
	public int getPerDuration() {
		return this.perDuration;
	}

	public void setPerDuration(int perDuration) {
		this.perDuration = perDuration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PER_CREATION_DATE", nullable = false, length = 19)
	public Date getPerCreationDate() {
		return this.perCreationDate;
	}

	public void setPerCreationDate(Date perCreationDate) {
		this.perCreationDate = perCreationDate;
	}

	@Column(name = "PER_PRICE", nullable = false, precision = 8)
	public float getPerPrice() {
		return this.perPrice;
	}

	public void setPerPrice(float perPrice) {
		this.perPrice = perPrice;
	}

	@Column(name = "PER_RANK", nullable = false)
	public int getPerRank() {
		return this.perRank;
	}

	public void setPerRank(int perRank) {
		this.perRank = perRank;
	}

	@Column(name = "PER_POSTER")
	public byte[] getPerPoster() {
		return this.perPoster;
	}

	public void setPerPoster(byte[] perPoster) {
		this.perPoster = perPoster;
	}

	@Column(name = "PER_DESCRIPTION", length = 200)
	public String getPerDescription() {
		return this.perDescription;
	}

	public void setPerDescription(String perDescription) {
		this.perDescription = perDescription;
	}

	@SuppressWarnings("rawtypes")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "performance")
	public Set getActorperformanceses() {
		return this.actorperformanceses;
	}

	@SuppressWarnings("rawtypes")
	public void setActorperformanceses(Set actorperformanceses) {
		this.actorperformanceses = actorperformanceses;
	}

	@SuppressWarnings("rawtypes")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "performance")
	public Set getEvents() {
		return this.events;
	}

	@SuppressWarnings("rawtypes")
	public void setEvents(Set events) {
		this.events = events;
	}

}
