package com.management.entities;
// Generated Feb 23, 2018 5:00:46 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * @author Zivko Stanisic
 * Props generated by hbm2java
 */
@SuppressWarnings("serial")
public class Props implements java.io.Serializable {

	private int propsId;
	private FanZone fanZone;
	private User user;
	private String propsName;
	private boolean propsUsed;
	private char propsType;
	private Date propsDeadline;
	private float propsPrice;
	private byte[] propsImage;
	private String propsDesc;

	public Props() {
	}

	public Props(int propsId, FanZone fanZone, User user, String propsName, boolean propsUsed, char propsType,
			Date propsDeadline, float propsPrice) {
		this.propsId = propsId;
		this.fanZone = fanZone;
		this.user = user;
		this.propsName = propsName;
		this.propsUsed = propsUsed;
		this.propsType = propsType;
		this.propsDeadline = propsDeadline;
		this.propsPrice = propsPrice;
	}

	public Props(int propsId, FanZone fanZone, User user, String propsName, boolean propsUsed, char propsType,
			Date propsDeadline, float propsPrice, byte[] propsImage, String propsDesc) {
		this.propsId = propsId;
		this.fanZone = fanZone;
		this.user = user;
		this.propsName = propsName;
		this.propsUsed = propsUsed;
		this.propsType = propsType;
		this.propsDeadline = propsDeadline;
		this.propsPrice = propsPrice;
		this.propsImage = propsImage;
		this.propsDesc = propsDesc;
	}

	public int getPropsId() {
		return this.propsId;
	}

	public void setPropsId(int propsId) {
		this.propsId = propsId;
	}

	public FanZone getFanZone() {
		return this.fanZone;
	}

	public void setFanZone(FanZone fanZone) {
		this.fanZone = fanZone;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPropsName() {
		return this.propsName;
	}

	public void setPropsName(String propsName) {
		this.propsName = propsName;
	}

	public boolean isPropsUsed() {
		return this.propsUsed;
	}

	public void setPropsUsed(boolean propsUsed) {
		this.propsUsed = propsUsed;
	}

	public char getPropsType() {
		return this.propsType;
	}

	public void setPropsType(char propsType) {
		this.propsType = propsType;
	}

	public Date getPropsDeadline() {
		return this.propsDeadline;
	}

	public void setPropsDeadline(Date propsDeadline) {
		this.propsDeadline = propsDeadline;
	}

	public float getPropsPrice() {
		return this.propsPrice;
	}

	public void setPropsPrice(float propsPrice) {
		this.propsPrice = propsPrice;
	}

	public byte[] getPropsImage() {
		return this.propsImage;
	}

	public void setPropsImage(byte[] propsImage) {
		this.propsImage = propsImage;
	}

	public String getPropsDesc() {
		return this.propsDesc;
	}

	public void setPropsDesc(String propsDesc) {
		this.propsDesc = propsDesc;
	}

}
