package com.management.entities;
// Generated Mar 4, 2018 4:33:07 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author Zivko Stanisic
 * Props generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "props", catalog = "isa")
public class Props implements java.io.Serializable {

	private int propsId;
	private FanZone fanZone;
	private User user;
	private String propsName;
	private boolean propsUsed;
	private char propsType;
	private Date propsDeadline;
	private float propsPrice;
	private byte[] propsImage;
	private String propsDesc;

	public Props() {
	}

	public Props(int propsId, FanZone fanZone, User user, String propsName, boolean propsUsed, char propsType,
			Date propsDeadline, float propsPrice) {
		this.propsId = propsId;
		this.fanZone = fanZone;
		this.user = user;
		this.propsName = propsName;
		this.propsUsed = propsUsed;
		this.propsType = propsType;
		this.propsDeadline = propsDeadline;
		this.propsPrice = propsPrice;
	}

	public Props(int propsId, FanZone fanZone, User user, String propsName, boolean propsUsed, char propsType,
			Date propsDeadline, float propsPrice, byte[] propsImage, String propsDesc) {
		this.propsId = propsId;
		this.fanZone = fanZone;
		this.user = user;
		this.propsName = propsName;
		this.propsUsed = propsUsed;
		this.propsType = propsType;
		this.propsDeadline = propsDeadline;
		this.propsPrice = propsPrice;
		this.propsImage = propsImage;
		this.propsDesc = propsDesc;
	}

	@Id

	@Column(name = "PROPS_ID", unique = true, nullable = false)
	public int getPropsId() {
		return this.propsId;
	}

	public void setPropsId(int propsId) {
		this.propsId = propsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FAN_ZONE_ID", nullable = false)
	public FanZone getFanZone() {
		return this.fanZone;
	}

	public void setFanZone(FanZone fanZone) {
		this.fanZone = fanZone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "PROPS_NAME", nullable = false, length = 50)
	public String getPropsName() {
		return this.propsName;
	}

	public void setPropsName(String propsName) {
		this.propsName = propsName;
	}

	@Column(name = "PROPS_USED", nullable = false)
	public boolean isPropsUsed() {
		return this.propsUsed;
	}

	public void setPropsUsed(boolean propsUsed) {
		this.propsUsed = propsUsed;
	}

	@Column(name = "PROPS_TYPE", nullable = false, length = 1)
	public char getPropsType() {
		return this.propsType;
	}

	public void setPropsType(char propsType) {
		this.propsType = propsType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PROPS_DEADLINE", nullable = false, length = 19)
	public Date getPropsDeadline() {
		return this.propsDeadline;
	}

	public void setPropsDeadline(Date propsDeadline) {
		this.propsDeadline = propsDeadline;
	}

	@Column(name = "PROPS_PRICE", nullable = false, precision = 8)
	public float getPropsPrice() {
		return this.propsPrice;
	}

	public void setPropsPrice(float propsPrice) {
		this.propsPrice = propsPrice;
	}

	@Column(name = "PROPS_IMAGE")
	public byte[] getPropsImage() {
		return this.propsImage;
	}

	public void setPropsImage(byte[] propsImage) {
		this.propsImage = propsImage;
	}

	@Column(name = "PROPS_DESC", length = 120)
	public String getPropsDesc() {
		return this.propsDesc;
	}

	public void setPropsDesc(String propsDesc) {
		this.propsDesc = propsDesc;
	}

}
