package com.management.entities;

// Generated Apr 15, 2018 9:26:22 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Rankscale generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "rankscale", catalog = "isa")
public class Rankscale implements java.io.Serializable {

	private int scaleId;
	private User user;
	private int scaleBronze;
	private int scaleSilver;
	private int scaleGold;
	private boolean scaleActive;

	public Rankscale() {
	}

	public Rankscale(int scaleId, User user, int scaleBronze, int scaleSilver,
			int scaleGold, boolean scaleActive) {
		this.scaleId = scaleId;
		this.user = user;
		this.scaleBronze = scaleBronze;
		this.scaleSilver = scaleSilver;
		this.scaleGold = scaleGold;
		this.scaleActive = scaleActive;
	}

	@Id
	@GenericGenerator(name="generator" , strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "SCALE_ID", unique = true, nullable = false)
	public int getScaleId() {
		return this.scaleId;
	}

	public void setScaleId(int scaleId) {
		this.scaleId = scaleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "SCALE_BRONZE", nullable = false)
	public int getScaleBronze() {
		return this.scaleBronze;
	}

	public void setScaleBronze(int scaleBronze) {
		this.scaleBronze = scaleBronze;
	}

	@Column(name = "SCALE_SILVER", nullable = false)
	public int getScaleSilver() {
		return this.scaleSilver;
	}

	public void setScaleSilver(int scaleSilver) {
		this.scaleSilver = scaleSilver;
	}

	@Column(name = "SCALE_GOLD", nullable = false)
	public int getScaleGold() {
		return this.scaleGold;
	}

	public void setScaleGold(int scaleGold) {
		this.scaleGold = scaleGold;
	}

	@Column(name = "SCALE_ACTIVE", nullable = false)
	public boolean isScaleActive() {
		return this.scaleActive;
	}

	public void setScaleActive(boolean scaleActive) {
		this.scaleActive = scaleActive;
	}

}
