package com.management.entities;
// Generated Apr 18, 2018 12:50:36 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Reservation generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "reservation", catalog = "isa")
public class Reservation implements java.io.Serializable {

	private int reservationId;
	private Props props;
	private User user;

	public Reservation() {
	}

	public Reservation(int reservationId, Props props, User user) {
		this.reservationId = reservationId;
		this.props = props;
		this.user = user;
	}

	@Id
	@GenericGenerator(name="generator" , strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "RESERVATION_ID", unique = true, nullable = false)
	public int getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(int reservationId) {
		this.reservationId = reservationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROPS_ID", nullable = false)
	public Props getProps() {
		return this.props;
	}

	public void setProps(Props props) {
		this.props = props;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
