package com.management.entities;
// Generated Feb 23, 2018 5:00:46 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * @author Zivko Stanisic
 * Seat generated by hbm2java
 */
@SuppressWarnings("serial")
public class Seat implements java.io.Serializable {

	private int seatId;
	private Hall hall;
	private User user;
	private boolean seatTaken;
	private Date seatModified;

	public Seat() {
	}

	public Seat(int seatId, Hall hall, boolean seatTaken, Date seatModified) {
		this.seatId = seatId;
		this.hall = hall;
		this.seatTaken = seatTaken;
		this.seatModified = seatModified;
	}

	public Seat(int seatId, Hall hall, User user, boolean seatTaken, Date seatModified) {
		this.seatId = seatId;
		this.hall = hall;
		this.user = user;
		this.seatTaken = seatTaken;
		this.seatModified = seatModified;
	}

	public int getSeatId() {
		return this.seatId;
	}

	public void setSeatId(int seatId) {
		this.seatId = seatId;
	}

	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public boolean isSeatTaken() {
		return this.seatTaken;
	}

	public void setSeatTaken(boolean seatTaken) {
		this.seatTaken = seatTaken;
	}

	public Date getSeatModified() {
		return this.seatModified;
	}

	public void setSeatModified(Date seatModified) {
		this.seatModified = seatModified;
	}

}
