package com.management.entities;
// Generated Apr 18, 2018 12:50:36 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Segment generated by hbm2java
 */
@Entity
@Table(name = "segment", catalog = "isa")
public class Segment implements java.io.Serializable {

	private int segId;
	private Hall hall;
	private String segName;
	private int segPosition;
	private int segNumberOfSeats;
	private Set<Seat> seats = new HashSet<Seat>(0);

	public Segment() {
	}

	public Segment(int segId, Hall hall, String segName, int segPosition, int segNumberOfSeats) {
		this.segId = segId;
		this.hall = hall;
		this.segName = segName;
		this.segPosition = segPosition;
		this.segNumberOfSeats = segNumberOfSeats;
	}

	public Segment(int segId, Hall hall, String segName, int segPosition, int segNumberOfSeats, Set<Seat> seats) {
		this.segId = segId;
		this.hall = hall;
		this.segName = segName;
		this.segPosition = segPosition;
		this.segNumberOfSeats = segNumberOfSeats;
		this.seats = seats;
	}

	@Id
	@GenericGenerator(name="generator" , strategy="increment")
	@GeneratedValue(generator="generator")
	@Column(name = "SEG_ID", unique = true, nullable = false)
	public int getSegId() {
		return this.segId;
	}

	public void setSegId(int segId) {
		this.segId = segId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HALL_ID", nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@Column(name = "SEG_NAME", nullable = false, length = 50)
	public String getSegName() {
		return this.segName;
	}

	public void setSegName(String segName) {
		this.segName = segName;
	}

	@Column(name = "SEG_POSITION", nullable = false)
	public int getSegPosition() {
		return this.segPosition;
	}

	public void setSegPosition(int segPosition) {
		this.segPosition = segPosition;
	}

	@Column(name = "SEG_NUMBER_OF_SEATS", nullable = false)
	public int getSegNumberOfSeats() {
		return this.segNumberOfSeats;
	}

	public void setSegNumberOfSeats(int segNumberOfSeats) {
		this.segNumberOfSeats = segNumberOfSeats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "segment")
	public Set<Seat> getSeats() {
		return this.seats;
	}

	public void setSeats(Set<Seat> seats) {
		this.seats = seats;
	}

}
